- name: installing the mysql server and configure
  hosts: mysql
  become: yes
  vars:
    mysql_username: root
    mysql_pwd: ExpenseApp@1
    mysql_host: mysql.sn2.online
  tasks:
  - name: install the mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: start the service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: Get MySQL version with non-default credentials
    community.mysql.mysql_info:
      login_user: "{{ mysql_username }}"
      login_password: "{{ mysql_pwd }}"
      local_host: "{{ mysql_host }}"
    register: mysql_info
  
  - name: print the output of the above command
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

